# Generated by Django 4.1.7 on 2023-07-31 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Place',
            new_name='Team',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='name',
            new_name='label',
        ),
    ]
